### ISSUE TITLE
/dev/rdisk0:  Resource busy , /dev/rdisk1: No such file or directory 

### ISSUE THREAD

**Issue by chocointed** [palera1n/palera1n#152]
**Describe the bug**
./palera1n.sh unable to access rdisk0/rdisk1

**Expected behavior**
Accepting cat request to ramdisk's rdisk0/rdisk1

**Screenshots**
rdisk0 palera1n.sh logs: https://paste.ee/p/iq2yy
rdisk0 ramdisk ssh logs: https://paste.ee/p/meLmZ
rdisk1 palera1n.sh logs: https://paste.ee/p/ecbGY
rdisk1 ramdisk ssh logs: https://paste.ee/p/wAG56

**Info (please complete the following information):**
- iDevice's version: iPad7,4 15.0.2
- Computer OS and version: macOS Big Sur
- The command you ran: ./palera1n.sh --tweaks 15.0.2 --debug

**Debug log**
rdisk0 palera1n.sh logs: https://paste.ee/p/iq2yy
rdisk0 ramdisk ssh logs: https://paste.ee/p/meLmZ
rdisk1 palera1n.sh logs: https://paste.ee/p/ecbGY
rdisk1 ramdisk ssh logs: https://paste.ee/p/wAG56

**Comment by kristenlc** [comment]
Without looking at the logs, I can say I had this exact issue before and it was caused by running SSHRD_Script before running palera1n without a reboot, or trying to run palera1n twice without a reboot. My circumstances were using High Siera though not Big Sur. Rebooting the computer fixed the issue in both cases for me. Not sure if it will help in your case.
