### ISSUE TITLE
shell script downloads from wrong repo

### ISSUE THREAD

**Issue by relative** [palera1n/palera1n#169]
https://github.com/palera1n/palera1n/blob/421dda3e2f88f831621929137c4ac87194d76093/palera1n.sh#L210

The script downloads the gaster build artifact from [verygenericname/gaster](https://github.com/verygenericname/gaster) rather than the [repository on the org](https://github.com/palera1n/gaster). if this users name is changed in the future and the script is not updated someone could theoretically have the script download a malicious gaster binary

**Comment by verygenericname** [comment]
its not the wrong repo, my username will never change

**Comment by verygenericname** [comment]
Besides, I have access over this repository too

**Comment by relative** [comment]
> its not the wrong repo, my username will never change

it was a hypothetical. still this seems odd as the org doesn't have control over the repo & **binaries run on the end users machine**.

feel free to close if wontfix.

**Comment by verygenericname** [comment]
I can give them access, but the reason it was my repo in the first place is this is heavily based over SSHRD_Script

**Comment by verygenericname** [comment]
and theres such thing as source code

**Comment by itsnebulalol** [comment]
It downloads gaster from Nathan's fork. He is in the org and has control, and he's trusted. He also stated that he probably would never change his GitHub name.

We reused code from SSHRD_Script since it did something similar, which is why we use Nathan's gaster fork too.

**Comment by relative** [comment]
> and theres such thing as source code

When you can change the source code without oversight this isn't an argument lol

**Comment by kristenlc** [comment]
I think what @relative is trying to say is instead the org should have gaster as palera1n/gaster and give @verygenericname read/ write access to the palera1n/gaster repo since he is a trusted developer of the code, and if anything needs to be updated in gaster that palera1n should take advantage off then @itsnebulalol or @verygenericname can run git pull from the origin verygenericname/gaster on the palera1n/gaster repo.

the benefits is then the palera1n/gaster repo is only updated with the latest changes from verygenericname/gaster if it is reviewed upon, is considered necessary to palera1n, and a git pull is made upon the repo. it is more safe since palera1n is downloading third party code in the script and running it without asking the users' consent right now.

@verygenericname is a very trusted developer in this project and there is nothing to worry about in that sense, what @relative was just pointing out was the potential security flaw in the way it is done right now nothing more.

in my own personal opinion i think that part of the script should be removed entirely and instead gaster should be added as a submodule of palera1n and it gets downloaded automatically when you close palera1n, cause then the submodule is only updated for palera1n when it is necessary and the team members have full control on when and how it gets updated for security

**Comment by kristenlc** [comment]
the potential issue with the way it is right now is that ok `gaster reset` is now `gaster reset_usb` in the palera1n.sh script so now if someone does git pull on palera1n and run the script then it will fail since gaster is not updated and `gaster reset_usb` is not present on the older version everyone already has on their computers, and it will only update to the latest if the binary is missing from the `$dir` folder. so now anyone with palera1n if they run git pull it will not work until they delete `binaries/Darwin/gaster` or `binaries/Linux/gaster` and re run the script.

you could fix this by having gaster as a submodule that gets updated anytime palera1n is updated and code is updated to reflect those changes, and then put in the palera1n script to `cd gaster` and `git pull` and `git reset --hard < commit >` to the commit that is being used by the code for palera1n to prevent palera1n from not working.
