### ISSUE TITLE
How to boot into normal mode without PC?

### ISSUE THREAD

**Issue by wahidulislamriyad** [palera1n/palera1n#183]
Sometime, if anyhow my phone's battery dies or reboots, it gets stucked into recovery mode. It's too much painful when it happens when I'm outside. I can't even use my phone to call emergency. It's really a serious issue.

I found this command in **postboot.sh**
_nvram auto-boot=false_

Maybe this command is creating this issues. I have tried to set it to true, but still no luck. Everytime my phone reboots, gets stucked into recovery. No way to boot into normmal mode.

Thanks to all the developers for making this great script. I have waited for more than 1 year for this jailbreak.

**Comment by wahidulislamriyad** [comment]
I have **SafeShutdown** tweak purchased before. This tweak _works great_. But it will save the jailbreak when battery is dying. But What to do when phone is rebooted?

**Comment by wahidulislamriyad** [comment]
nvram auto-boot=true
command worked. now i can reboot to normal mode without PC.

**Comment by wahidulislamriyad** [comment]
> That’s not an issue. It’s intentional.
> 
> If your device reboots into stock, the jailbreak gets reverted. That’s why the jailbreak is tethered in the first place, so you don’t lose your tweaks each time you reboot.

I’ve never experienced this. Palera1n is just like Checkra1n. It doesn’t get revert to stock when booted into normal mode.

**Comment by mineLdiver** [comment]
> > That’s not an issue. It’s intentional.
> > If your device reboots into stock, the jailbreak gets reverted. That’s why the jailbreak is tethered in the first place, so you don’t lose your tweaks each time you reboot.
> 
> I’ve never experienced this. Palera1n is just like Checkra1n. It doesn’t get revert to stock when booted into normal mode. And also, nothing is removed. Everything will be kept.

I have no idea how you've managed to make your tweaks stay, but iOS 15 introduced sealed root. Even if root gets mounted as r/w, it gets reverted back to its original state on next boot. Which is why palera1n is intentionally tethered, so we can avoid booting normally and getting the tweaks reverted.
It's explained better here - https://github.com/itsnebulalol/ios15-tweaks

Also, I guess, that's the reason checkra1n wasn't updated to iOS 15 yet - because there's no way to get proper root and stay semi-tethered.

**Comment by wahidulislamriyad** [comment]
I have jailbroken my iPhone 7 before using checkra1n and also unc0ver. Maybe they have left some exploits.

As far as I remember, I have experienced that kind of issue when palera1n was released. Sileo, NewTerm everything was gone every time I rebooted into stock. Tips app were totally broken. Even if I re-downloaded. But having a full reset of my device, no more issues. Working just like the checkra1n. All files left intact except those tweaks running. Everything works perfectly when I re-jailbreak.

I think, palera1n can also work as an app. As like unc0ver before.

**Comment by mineLdiver** [comment]
Exploits take advantage of system vulnerabilities. Even if "they have left some exploits", the vulnerabilities are patched, making them useless.

And no, palera1n can't *ever* be an app, because it exploits the device in DFU through USB. Literally physically impossible, and same reason checkra1n will never be an app. That's just not how checkm8 works.
