### ISSUE TITLE
Wifi is grayed out and not working

### ISSUE THREAD

**Issue by Ahmad4MayLod** [palera1n/palera1n#430]
### Device

iPhone X

### Version

iOS 16.7.6

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

**After jailbreak iOS 16.7.6 the wifi is grayed out and not working, same issue on two iPhones X**
**This only happens in the latest version (v2.0.0 beta 9.2).**
**After jailbreak with old version (v2.0.0 beta 9.1) wifi is working and there's no problem.**

![IMG_7959](https://github.com/palera1n/palera1n/assets/11242169/80c0b67a-7980-450f-8068-383d9fda050f)

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
This is a common-issue amongst tools that use tools like checkra1n, the fix is usually to userspace reboot after booting jailbroken. 

Solution:
```
ssh root@127.0.0.1 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ProxyCommand=inetcat 44"
launchctl reboot userspace
```
Pass: `alpine`

From my experience this really only happens uncommonly when jailbreaking, sometimes I need to userspace reboot and sometimes I don't, its a hit or miss.

**Comment by Ahmad4MayLod** [comment]
well, didn't work, 
( \h:\w \u$ client_loop: send disconnect: Broken pipe )
