### ISSUE TITLE
Exploit not working with iPhone X

### ISSUE THREAD

**Issue by vj0shii** [palera1n/palera1n#469]
### Device

iPhone X

### Version

iOS 16.7.8

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

After running the command line the exploit get's stuck at 
```
 - [08/23/24 17:52:05] <Verbose>: Device should now reconnect in download mode
 - [08/23/24 17:52:05] <Verbose>: DFU mode device disconnected
 - [08/23/24 17:52:25] <Error>: Timed out waiting for download mode (error code: -status_exploit_timeout_error)
 ```

On trying to disconnect and reconnect, the exploit completes and I see the palera1n screen in the device

<img width="568" alt="image" src="https://github.com/user-attachments/assets/54868b15-4daa-41a7-8ede-e081883d55a4">

After the palera1n screen, the device shows black screen and apple logo (I think the device just rebooted)

Cannot find the loader application in home screen after this

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
Check common-issues here https://docs.palera.in/docs/troubleshoot/troubleshooting-steps/#timed-out-waiting-for-download-mode for steps on how to troubleshoot that and (evidently) fix it.

Since this is a common issue which is really out of our control, I will close this as it doesn't have any significance to us.
