### ISSUE TITLE
Timed out waiting for download mode - Black screen

### ISSUE THREAD

**Issue by Byrgir** [palera1n/palera1n#505]
### Device

iphone SE

### Version

IOS 15.8.2

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

Hello,
I tried to jailbreak an Iphone SE with IOS 15.8.2 and I still have the same problem: Timed out waiting for download mode.

My computer is configured with ubuntu and I have an Intel chip inside. As far as the iPhone is concerned, I've entered DFU mode, and when it gets to ‘<Verbose>: DFU mode device disconnected’, nothing happens. The screen stays black and I can't enter dowload mode. I've tried several cables, plugged and unplugged several times, but nothing changes. The Apple logo never appears. 

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by ElliesSurviving** [comment]
try running with sudo, try using different ports and cables, unfortunately this issue cant really be fixed by the team due to the fact its a checkra1n problem which is a closed source component of palera1n

**Comment by khcrysalis** [comment]
Since this is a common issue that we don't have control of due to a variety of reasons, I will be closing this.

Make sure you've ran the common solutions from our docs regarding ["Timed out waiting for download mode"](https://docs.palera.in/docs/troubleshoot/troubleshooting-steps/#timed-out-waiting-for-download-mode), and troubleshoot on your own to see if any of your setup could be causing issues.
